/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedEligibilityRouteImport } from './routes/_authenticated/eligibility'
import { Route as AuthenticatedFamilyRouteImport } from './routes/_authenticated/family'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as CompanyAuthenticatedRouteImport } from './routes/company/_authenticated'
import { Route as CompanyLoginRouteImport } from './routes/company/login'
import { Route as CompanyRegisterRouteImport } from './routes/company/register'
import { Route as JobsAuthenticatedRouteImport } from './routes/jobs/_authenticated'
import { Route as JobsAdminRouteImport } from './routes/jobs/admin'
import { Route as JobsForgotPasswordRouteImport } from './routes/jobs/forgot-password'
import { Route as JobsLoginRouteImport } from './routes/jobs/login'
import { Route as JobsOnboardingRouteImport } from './routes/jobs/onboarding'
import { Route as JobsSignupRouteImport } from './routes/jobs/signup'
import { Route as JobsVerifyEmailRouteImport } from './routes/jobs/verify-email'
import { Route as AuthenticatedSchemesIndexRouteImport } from './routes/_authenticated/schemes.index'
import { Route as AuthenticatedSchemesSlugRouteImport } from './routes/_authenticated/schemes.$slug'
import { Route as CompanyAuthenticatedApplicationsRouteImport } from './routes/company/_authenticated/applications'
import { Route as CompanyAuthenticatedDashboardRouteImport } from './routes/company/_authenticated/dashboard'
import { Route as CompanyAuthenticatedJobsRouteImport } from './routes/company/_authenticated/jobs'
import { Route as CompanyAuthenticatedSettingsRouteImport } from './routes/company/_authenticated/settings'
import { Route as JobsAuthenticatedApplicationsRouteImport } from './routes/jobs/_authenticated/applications'
import { Route as JobsAuthenticatedDashboardRouteImport } from './routes/jobs/_authenticated/dashboard'
import { Route as JobsAuthenticatedProfileRouteImport } from './routes/jobs/_authenticated/profile'
import { Route as JobsAuthenticatedResumeRouteImport } from './routes/jobs/_authenticated/resume'
import { Route as JobsAuthenticatedSavedRouteImport } from './routes/jobs/_authenticated/saved'
import { Route as JobsAuthenticatedSearchRouteImport } from './routes/jobs/_authenticated/search'
import { Route as JobsAuthenticatedSettingsRouteImport } from './routes/jobs/_authenticated/settings'
import { Route as JobsAdminAuditLogsRouteImport } from './routes/jobs/admin/audit-logs'
import { Route as JobsAdminCompaniesRouteImport } from './routes/jobs/admin/companies'
import { Route as JobsAdminDashboardRouteImport } from './routes/jobs/admin/dashboard'
import { Route as JobsAdminJobsRouteImport } from './routes/jobs/admin/jobs'
import { Route as JobsAdminLoginRouteImport } from './routes/jobs/admin/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEligibilityRoute =
  AuthenticatedEligibilityRouteImport.update({
    id: '/eligibility',
    path: '/eligibility',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilyRoute = AuthenticatedFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CompanyAuthenticatedRoute = CompanyAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyLoginRoute = CompanyLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyRegisterRoute = CompanyRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => CompanyRoute,
} as any)
const JobsAuthenticatedRoute = JobsAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => JobsRoute,
} as any)
const JobsAdminRoute = JobsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => JobsRoute,
} as any)
const JobsForgotPasswordRoute = JobsForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => JobsRoute,
} as any)
const JobsLoginRoute = JobsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => JobsRoute,
} as any)
const JobsOnboardingRoute = JobsOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => JobsRoute,
} as any)
const JobsSignupRoute = JobsSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => JobsRoute,
} as any)
const JobsVerifyEmailRoute = JobsVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => JobsRoute,
} as any)
const AuthenticatedSchemesIndexRoute =
  AuthenticatedSchemesIndexRouteImport.update({
    id: '/schemes/',
    path: '/schemes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchemesSlugRoute =
  AuthenticatedSchemesSlugRouteImport.update({
    id: '/schemes/$slug',
    path: '/schemes/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CompanyAuthenticatedApplicationsRoute =
  CompanyAuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => CompanyAuthenticatedRoute,
  } as any)
const CompanyAuthenticatedDashboardRoute =
  CompanyAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => CompanyAuthenticatedRoute,
  } as any)
const CompanyAuthenticatedJobsRoute =
  CompanyAuthenticatedJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => CompanyAuthenticatedRoute,
  } as any)
const CompanyAuthenticatedSettingsRoute =
  CompanyAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => CompanyAuthenticatedRoute,
  } as any)
const JobsAuthenticatedApplicationsRoute =
  JobsAuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => JobsAuthenticatedRoute,
  } as any)
const JobsAuthenticatedDashboardRoute =
  JobsAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => JobsAuthenticatedRoute,
  } as any)
const JobsAuthenticatedProfileRoute =
  JobsAuthenticatedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => JobsAuthenticatedRoute,
  } as any)
const JobsAuthenticatedResumeRoute = JobsAuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => JobsAuthenticatedRoute,
} as any)
const JobsAuthenticatedSavedRoute = JobsAuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => JobsAuthenticatedRoute,
} as any)
const JobsAuthenticatedSearchRoute = JobsAuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => JobsAuthenticatedRoute,
} as any)
const JobsAuthenticatedSettingsRoute =
  JobsAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => JobsAuthenticatedRoute,
  } as any)
const JobsAdminAuditLogsRoute = JobsAdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => JobsAdminRoute,
} as any)
const JobsAdminCompaniesRoute = JobsAdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => JobsAdminRoute,
} as any)
const JobsAdminDashboardRoute = JobsAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => JobsAdminRoute,
} as any)
const JobsAdminJobsRoute = JobsAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => JobsAdminRoute,
} as any)
const JobsAdminLoginRoute = JobsAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => JobsAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/company': typeof CompanyRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/applications': typeof AuthenticatedApplicationsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/eligibility': typeof AuthenticatedEligibilityRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/company/login': typeof CompanyLoginRoute
  '/company/register': typeof CompanyRegisterRoute
  '/jobs/admin': typeof JobsAdminRouteWithChildren
  '/jobs/forgot-password': typeof JobsForgotPasswordRoute
  '/jobs/login': typeof JobsLoginRoute
  '/jobs/onboarding': typeof JobsOnboardingRoute
  '/jobs/signup': typeof JobsSignupRoute
  '/jobs/verify-email': typeof JobsVerifyEmailRoute
  '/schemes/$slug': typeof AuthenticatedSchemesSlugRoute
  '/company/applications': typeof CompanyAuthenticatedApplicationsRoute
  '/company/dashboard': typeof CompanyAuthenticatedDashboardRoute
  '/company/jobs': typeof CompanyAuthenticatedJobsRoute
  '/company/settings': typeof CompanyAuthenticatedSettingsRoute
  '/jobs/applications': typeof JobsAuthenticatedApplicationsRoute
  '/jobs/dashboard': typeof JobsAuthenticatedDashboardRoute
  '/jobs/profile': typeof JobsAuthenticatedProfileRoute
  '/jobs/resume': typeof JobsAuthenticatedResumeRoute
  '/jobs/saved': typeof JobsAuthenticatedSavedRoute
  '/jobs/search': typeof JobsAuthenticatedSearchRoute
  '/jobs/settings': typeof JobsAuthenticatedSettingsRoute
  '/jobs/admin/audit-logs': typeof JobsAdminAuditLogsRoute
  '/jobs/admin/companies': typeof JobsAdminCompaniesRoute
  '/jobs/admin/dashboard': typeof JobsAdminDashboardRoute
  '/jobs/admin/jobs': typeof JobsAdminJobsRoute
  '/jobs/admin/login': typeof JobsAdminLoginRoute
  '/schemes/': typeof AuthenticatedSchemesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/company': typeof CompanyRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/applications': typeof AuthenticatedApplicationsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/eligibility': typeof AuthenticatedEligibilityRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/company/login': typeof CompanyLoginRoute
  '/company/register': typeof CompanyRegisterRoute
  '/jobs/admin': typeof JobsAdminRouteWithChildren
  '/jobs/forgot-password': typeof JobsForgotPasswordRoute
  '/jobs/login': typeof JobsLoginRoute
  '/jobs/onboarding': typeof JobsOnboardingRoute
  '/jobs/signup': typeof JobsSignupRoute
  '/jobs/verify-email': typeof JobsVerifyEmailRoute
  '/schemes/$slug': typeof AuthenticatedSchemesSlugRoute
  '/company/applications': typeof CompanyAuthenticatedApplicationsRoute
  '/company/dashboard': typeof CompanyAuthenticatedDashboardRoute
  '/company/jobs': typeof CompanyAuthenticatedJobsRoute
  '/company/settings': typeof CompanyAuthenticatedSettingsRoute
  '/jobs/applications': typeof JobsAuthenticatedApplicationsRoute
  '/jobs/dashboard': typeof JobsAuthenticatedDashboardRoute
  '/jobs/profile': typeof JobsAuthenticatedProfileRoute
  '/jobs/resume': typeof JobsAuthenticatedResumeRoute
  '/jobs/saved': typeof JobsAuthenticatedSavedRoute
  '/jobs/search': typeof JobsAuthenticatedSearchRoute
  '/jobs/settings': typeof JobsAuthenticatedSettingsRoute
  '/jobs/admin/audit-logs': typeof JobsAdminAuditLogsRoute
  '/jobs/admin/companies': typeof JobsAdminCompaniesRoute
  '/jobs/admin/dashboard': typeof JobsAdminDashboardRoute
  '/jobs/admin/jobs': typeof JobsAdminJobsRoute
  '/jobs/admin/login': typeof JobsAdminLoginRoute
  '/schemes': typeof AuthenticatedSchemesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/company': typeof CompanyRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/eligibility': typeof AuthenticatedEligibilityRoute
  '/_authenticated/family': typeof AuthenticatedFamilyRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/company/_authenticated': typeof CompanyAuthenticatedRouteWithChildren
  '/company/login': typeof CompanyLoginRoute
  '/company/register': typeof CompanyRegisterRoute
  '/jobs/_authenticated': typeof JobsAuthenticatedRouteWithChildren
  '/jobs/admin': typeof JobsAdminRouteWithChildren
  '/jobs/forgot-password': typeof JobsForgotPasswordRoute
  '/jobs/login': typeof JobsLoginRoute
  '/jobs/onboarding': typeof JobsOnboardingRoute
  '/jobs/signup': typeof JobsSignupRoute
  '/jobs/verify-email': typeof JobsVerifyEmailRoute
  '/_authenticated/schemes/$slug': typeof AuthenticatedSchemesSlugRoute
  '/company/_authenticated/applications': typeof CompanyAuthenticatedApplicationsRoute
  '/company/_authenticated/dashboard': typeof CompanyAuthenticatedDashboardRoute
  '/company/_authenticated/jobs': typeof CompanyAuthenticatedJobsRoute
  '/company/_authenticated/settings': typeof CompanyAuthenticatedSettingsRoute
  '/jobs/_authenticated/applications': typeof JobsAuthenticatedApplicationsRoute
  '/jobs/_authenticated/dashboard': typeof JobsAuthenticatedDashboardRoute
  '/jobs/_authenticated/profile': typeof JobsAuthenticatedProfileRoute
  '/jobs/_authenticated/resume': typeof JobsAuthenticatedResumeRoute
  '/jobs/_authenticated/saved': typeof JobsAuthenticatedSavedRoute
  '/jobs/_authenticated/search': typeof JobsAuthenticatedSearchRoute
  '/jobs/_authenticated/settings': typeof JobsAuthenticatedSettingsRoute
  '/jobs/admin/audit-logs': typeof JobsAdminAuditLogsRoute
  '/jobs/admin/companies': typeof JobsAdminCompaniesRoute
  '/jobs/admin/dashboard': typeof JobsAdminDashboardRoute
  '/jobs/admin/jobs': typeof JobsAdminJobsRoute
  '/jobs/admin/login': typeof JobsAdminLoginRoute
  '/_authenticated/schemes/': typeof AuthenticatedSchemesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/company'
    | '/jobs'
    | '/applications'
    | '/assistant'
    | '/dashboard'
    | '/documents'
    | '/eligibility'
    | '/family'
    | '/notifications'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/company/login'
    | '/company/register'
    | '/jobs/admin'
    | '/jobs/forgot-password'
    | '/jobs/login'
    | '/jobs/onboarding'
    | '/jobs/signup'
    | '/jobs/verify-email'
    | '/schemes/$slug'
    | '/company/applications'
    | '/company/dashboard'
    | '/company/jobs'
    | '/company/settings'
    | '/jobs/applications'
    | '/jobs/dashboard'
    | '/jobs/profile'
    | '/jobs/resume'
    | '/jobs/saved'
    | '/jobs/search'
    | '/jobs/settings'
    | '/jobs/admin/audit-logs'
    | '/jobs/admin/companies'
    | '/jobs/admin/dashboard'
    | '/jobs/admin/jobs'
    | '/jobs/admin/login'
    | '/schemes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/company'
    | '/jobs'
    | '/applications'
    | '/assistant'
    | '/dashboard'
    | '/documents'
    | '/eligibility'
    | '/family'
    | '/notifications'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/company/login'
    | '/company/register'
    | '/jobs/admin'
    | '/jobs/forgot-password'
    | '/jobs/login'
    | '/jobs/onboarding'
    | '/jobs/signup'
    | '/jobs/verify-email'
    | '/schemes/$slug'
    | '/company/applications'
    | '/company/dashboard'
    | '/company/jobs'
    | '/company/settings'
    | '/jobs/applications'
    | '/jobs/dashboard'
    | '/jobs/profile'
    | '/jobs/resume'
    | '/jobs/saved'
    | '/jobs/search'
    | '/jobs/settings'
    | '/jobs/admin/audit-logs'
    | '/jobs/admin/companies'
    | '/jobs/admin/dashboard'
    | '/jobs/admin/jobs'
    | '/jobs/admin/login'
    | '/schemes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/company'
    | '/jobs'
    | '/_authenticated/applications'
    | '/_authenticated/assistant'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/eligibility'
    | '/_authenticated/family'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/saved'
    | '/_authenticated/settings'
    | '/company/_authenticated'
    | '/company/login'
    | '/company/register'
    | '/jobs/_authenticated'
    | '/jobs/admin'
    | '/jobs/forgot-password'
    | '/jobs/login'
    | '/jobs/onboarding'
    | '/jobs/signup'
    | '/jobs/verify-email'
    | '/_authenticated/schemes/$slug'
    | '/company/_authenticated/applications'
    | '/company/_authenticated/dashboard'
    | '/company/_authenticated/jobs'
    | '/company/_authenticated/settings'
    | '/jobs/_authenticated/applications'
    | '/jobs/_authenticated/dashboard'
    | '/jobs/_authenticated/profile'
    | '/jobs/_authenticated/resume'
    | '/jobs/_authenticated/saved'
    | '/jobs/_authenticated/search'
    | '/jobs/_authenticated/settings'
    | '/jobs/admin/audit-logs'
    | '/jobs/admin/companies'
    | '/jobs/admin/dashboard'
    | '/jobs/admin/jobs'
    | '/jobs/admin/login'
    | '/_authenticated/schemes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompanyRoute: typeof CompanyRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eligibility': {
      id: '/_authenticated/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof AuthenticatedEligibilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family': {
      id: '/_authenticated/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AuthenticatedFamilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/company/_authenticated': {
      id: '/company/_authenticated'
      path: ''
      fullPath: '/company'
      preLoaderRoute: typeof CompanyAuthenticatedRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/login': {
      id: '/company/login'
      path: '/login'
      fullPath: '/company/login'
      preLoaderRoute: typeof CompanyLoginRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/register': {
      id: '/company/register'
      path: '/register'
      fullPath: '/company/register'
      preLoaderRoute: typeof CompanyRegisterRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/jobs/_authenticated': {
      id: '/jobs/_authenticated'
      path: ''
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsAuthenticatedRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/admin': {
      id: '/jobs/admin'
      path: '/admin'
      fullPath: '/jobs/admin'
      preLoaderRoute: typeof JobsAdminRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/forgot-password': {
      id: '/jobs/forgot-password'
      path: '/forgot-password'
      fullPath: '/jobs/forgot-password'
      preLoaderRoute: typeof JobsForgotPasswordRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/login': {
      id: '/jobs/login'
      path: '/login'
      fullPath: '/jobs/login'
      preLoaderRoute: typeof JobsLoginRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/onboarding': {
      id: '/jobs/onboarding'
      path: '/onboarding'
      fullPath: '/jobs/onboarding'
      preLoaderRoute: typeof JobsOnboardingRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/signup': {
      id: '/jobs/signup'
      path: '/signup'
      fullPath: '/jobs/signup'
      preLoaderRoute: typeof JobsSignupRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/verify-email': {
      id: '/jobs/verify-email'
      path: '/verify-email'
      fullPath: '/jobs/verify-email'
      preLoaderRoute: typeof JobsVerifyEmailRouteImport
      parentRoute: typeof JobsRoute
    }
    '/_authenticated/schemes/': {
      id: '/_authenticated/schemes/'
      path: '/schemes'
      fullPath: '/schemes/'
      preLoaderRoute: typeof AuthenticatedSchemesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schemes/$slug': {
      id: '/_authenticated/schemes/$slug'
      path: '/schemes/$slug'
      fullPath: '/schemes/$slug'
      preLoaderRoute: typeof AuthenticatedSchemesSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/company/_authenticated/applications': {
      id: '/company/_authenticated/applications'
      path: '/applications'
      fullPath: '/company/applications'
      preLoaderRoute: typeof CompanyAuthenticatedApplicationsRouteImport
      parentRoute: typeof CompanyAuthenticatedRoute
    }
    '/company/_authenticated/dashboard': {
      id: '/company/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/company/dashboard'
      preLoaderRoute: typeof CompanyAuthenticatedDashboardRouteImport
      parentRoute: typeof CompanyAuthenticatedRoute
    }
    '/company/_authenticated/jobs': {
      id: '/company/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/company/jobs'
      preLoaderRoute: typeof CompanyAuthenticatedJobsRouteImport
      parentRoute: typeof CompanyAuthenticatedRoute
    }
    '/company/_authenticated/settings': {
      id: '/company/_authenticated/settings'
      path: '/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof CompanyAuthenticatedSettingsRouteImport
      parentRoute: typeof CompanyAuthenticatedRoute
    }
    '/jobs/_authenticated/applications': {
      id: '/jobs/_authenticated/applications'
      path: '/applications'
      fullPath: '/jobs/applications'
      preLoaderRoute: typeof JobsAuthenticatedApplicationsRouteImport
      parentRoute: typeof JobsAuthenticatedRoute
    }
    '/jobs/_authenticated/dashboard': {
      id: '/jobs/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/jobs/dashboard'
      preLoaderRoute: typeof JobsAuthenticatedDashboardRouteImport
      parentRoute: typeof JobsAuthenticatedRoute
    }
    '/jobs/_authenticated/profile': {
      id: '/jobs/_authenticated/profile'
      path: '/profile'
      fullPath: '/jobs/profile'
      preLoaderRoute: typeof JobsAuthenticatedProfileRouteImport
      parentRoute: typeof JobsAuthenticatedRoute
    }
    '/jobs/_authenticated/resume': {
      id: '/jobs/_authenticated/resume'
      path: '/resume'
      fullPath: '/jobs/resume'
      preLoaderRoute: typeof JobsAuthenticatedResumeRouteImport
      parentRoute: typeof JobsAuthenticatedRoute
    }
    '/jobs/_authenticated/saved': {
      id: '/jobs/_authenticated/saved'
      path: '/saved'
      fullPath: '/jobs/saved'
      preLoaderRoute: typeof JobsAuthenticatedSavedRouteImport
      parentRoute: typeof JobsAuthenticatedRoute
    }
    '/jobs/_authenticated/search': {
      id: '/jobs/_authenticated/search'
      path: '/search'
      fullPath: '/jobs/search'
      preLoaderRoute: typeof JobsAuthenticatedSearchRouteImport
      parentRoute: typeof JobsAuthenticatedRoute
    }
    '/jobs/_authenticated/settings': {
      id: '/jobs/_authenticated/settings'
      path: '/settings'
      fullPath: '/jobs/settings'
      preLoaderRoute: typeof JobsAuthenticatedSettingsRouteImport
      parentRoute: typeof JobsAuthenticatedRoute
    }
    '/jobs/admin/audit-logs': {
      id: '/jobs/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/jobs/admin/audit-logs'
      preLoaderRoute: typeof JobsAdminAuditLogsRouteImport
      parentRoute: typeof JobsAdminRoute
    }
    '/jobs/admin/companies': {
      id: '/jobs/admin/companies'
      path: '/companies'
      fullPath: '/jobs/admin/companies'
      preLoaderRoute: typeof JobsAdminCompaniesRouteImport
      parentRoute: typeof JobsAdminRoute
    }
    '/jobs/admin/dashboard': {
      id: '/jobs/admin/dashboard'
      path: '/dashboard'
      fullPath: '/jobs/admin/dashboard'
      preLoaderRoute: typeof JobsAdminDashboardRouteImport
      parentRoute: typeof JobsAdminRoute
    }
    '/jobs/admin/jobs': {
      id: '/jobs/admin/jobs'
      path: '/jobs'
      fullPath: '/jobs/admin/jobs'
      preLoaderRoute: typeof JobsAdminJobsRouteImport
      parentRoute: typeof JobsAdminRoute
    }
    '/jobs/admin/login': {
      id: '/jobs/admin/login'
      path: '/login'
      fullPath: '/jobs/admin/login'
      preLoaderRoute: typeof JobsAdminLoginRouteImport
      parentRoute: typeof JobsAdminRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEligibilityRoute: typeof AuthenticatedEligibilityRoute
  AuthenticatedFamilyRoute: typeof AuthenticatedFamilyRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSchemesSlugRoute: typeof AuthenticatedSchemesSlugRoute
  AuthenticatedSchemesIndexRoute: typeof AuthenticatedSchemesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEligibilityRoute: AuthenticatedEligibilityRoute,
  AuthenticatedFamilyRoute: AuthenticatedFamilyRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSchemesSlugRoute: AuthenticatedSchemesSlugRoute,
  AuthenticatedSchemesIndexRoute: AuthenticatedSchemesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CompanyAuthenticatedRouteChildren {
  CompanyAuthenticatedApplicationsRoute: typeof CompanyAuthenticatedApplicationsRoute
  CompanyAuthenticatedDashboardRoute: typeof CompanyAuthenticatedDashboardRoute
  CompanyAuthenticatedJobsRoute: typeof CompanyAuthenticatedJobsRoute
  CompanyAuthenticatedSettingsRoute: typeof CompanyAuthenticatedSettingsRoute
}

const CompanyAuthenticatedRouteChildren: CompanyAuthenticatedRouteChildren = {
  CompanyAuthenticatedApplicationsRoute: CompanyAuthenticatedApplicationsRoute,
  CompanyAuthenticatedDashboardRoute: CompanyAuthenticatedDashboardRoute,
  CompanyAuthenticatedJobsRoute: CompanyAuthenticatedJobsRoute,
  CompanyAuthenticatedSettingsRoute: CompanyAuthenticatedSettingsRoute,
}

const CompanyAuthenticatedRouteWithChildren =
  CompanyAuthenticatedRoute._addFileChildren(CompanyAuthenticatedRouteChildren)

interface CompanyRouteChildren {
  CompanyAuthenticatedRoute: typeof CompanyAuthenticatedRouteWithChildren
  CompanyLoginRoute: typeof CompanyLoginRoute
  CompanyRegisterRoute: typeof CompanyRegisterRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyAuthenticatedRoute: CompanyAuthenticatedRouteWithChildren,
  CompanyLoginRoute: CompanyLoginRoute,
  CompanyRegisterRoute: CompanyRegisterRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

interface JobsAuthenticatedRouteChildren {
  JobsAuthenticatedApplicationsRoute: typeof JobsAuthenticatedApplicationsRoute
  JobsAuthenticatedDashboardRoute: typeof JobsAuthenticatedDashboardRoute
  JobsAuthenticatedProfileRoute: typeof JobsAuthenticatedProfileRoute
  JobsAuthenticatedResumeRoute: typeof JobsAuthenticatedResumeRoute
  JobsAuthenticatedSavedRoute: typeof JobsAuthenticatedSavedRoute
  JobsAuthenticatedSearchRoute: typeof JobsAuthenticatedSearchRoute
  JobsAuthenticatedSettingsRoute: typeof JobsAuthenticatedSettingsRoute
}

const JobsAuthenticatedRouteChildren: JobsAuthenticatedRouteChildren = {
  JobsAuthenticatedApplicationsRoute: JobsAuthenticatedApplicationsRoute,
  JobsAuthenticatedDashboardRoute: JobsAuthenticatedDashboardRoute,
  JobsAuthenticatedProfileRoute: JobsAuthenticatedProfileRoute,
  JobsAuthenticatedResumeRoute: JobsAuthenticatedResumeRoute,
  JobsAuthenticatedSavedRoute: JobsAuthenticatedSavedRoute,
  JobsAuthenticatedSearchRoute: JobsAuthenticatedSearchRoute,
  JobsAuthenticatedSettingsRoute: JobsAuthenticatedSettingsRoute,
}

const JobsAuthenticatedRouteWithChildren =
  JobsAuthenticatedRoute._addFileChildren(JobsAuthenticatedRouteChildren)

interface JobsAdminRouteChildren {
  JobsAdminAuditLogsRoute: typeof JobsAdminAuditLogsRoute
  JobsAdminCompaniesRoute: typeof JobsAdminCompaniesRoute
  JobsAdminDashboardRoute: typeof JobsAdminDashboardRoute
  JobsAdminJobsRoute: typeof JobsAdminJobsRoute
  JobsAdminLoginRoute: typeof JobsAdminLoginRoute
}

const JobsAdminRouteChildren: JobsAdminRouteChildren = {
  JobsAdminAuditLogsRoute: JobsAdminAuditLogsRoute,
  JobsAdminCompaniesRoute: JobsAdminCompaniesRoute,
  JobsAdminDashboardRoute: JobsAdminDashboardRoute,
  JobsAdminJobsRoute: JobsAdminJobsRoute,
  JobsAdminLoginRoute: JobsAdminLoginRoute,
}

const JobsAdminRouteWithChildren = JobsAdminRoute._addFileChildren(
  JobsAdminRouteChildren,
)

interface JobsRouteChildren {
  JobsAuthenticatedRoute: typeof JobsAuthenticatedRouteWithChildren
  JobsAdminRoute: typeof JobsAdminRouteWithChildren
  JobsForgotPasswordRoute: typeof JobsForgotPasswordRoute
  JobsLoginRoute: typeof JobsLoginRoute
  JobsOnboardingRoute: typeof JobsOnboardingRoute
  JobsSignupRoute: typeof JobsSignupRoute
  JobsVerifyEmailRoute: typeof JobsVerifyEmailRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsAuthenticatedRoute: JobsAuthenticatedRouteWithChildren,
  JobsAdminRoute: JobsAdminRouteWithChildren,
  JobsForgotPasswordRoute: JobsForgotPasswordRoute,
  JobsLoginRoute: JobsLoginRoute,
  JobsOnboardingRoute: JobsOnboardingRoute,
  JobsSignupRoute: JobsSignupRoute,
  JobsVerifyEmailRoute: JobsVerifyEmailRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompanyRoute: CompanyRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
